name: sift

type: ruby

up:
  - ruby
  - bundler

commands:
  build: echo "noop" > /dev/null
  run-built: bundle exec exe/sift $@
  sift: bundle exec exe/sift $@
  sq: bundle exec exe/sq $@
  test: bundle exec rake test
  debug: SIFT_LOG_LEVEL=debug bundle exec exe/sift $@

check:
  test: bundle exec rake test
